name: Deploy CERCA Web to Vercel

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g vercel@latest
      - run: vercel deploy --prod --yes --cwd cerca-web --token="${{ secrets.VERCEL_TOKEN }}"